// prisma/seed.ts
// Seeds the 38 market rules into the database
// Run once after migration: npx prisma db seed

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const markets = [
  // ── SAFE MARKETS ──────────────────────────────────────────────────────
  {
    marketKey: 'double_chance_1x',
    marketName: 'Double Chance (Home or Draw)',
    marketGroup: 'Double Chance',
    riskCategory: 'SAFE' as const,
    minConfidence: 60, keepThreshold: 65, replaceThreshold: 45, removeThreshold: 35,
    requiredMetrics: ['form', 'homeAway', 'h2h'],
    formWeight: 0.35, homeAwayWeight: 0.25, h2hWeight: 0.20, goalTrendWeight: 0.05, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'result', safeAlternative: null,
  },
  {
    marketKey: 'double_chance_x2',
    marketName: 'Double Chance (Draw or Away)',
    marketGroup: 'Double Chance',
    riskCategory: 'SAFE' as const,
    minConfidence: 60, keepThreshold: 65, replaceThreshold: 45, removeThreshold: 35,
    requiredMetrics: ['form', 'homeAway', 'h2h'],
    formWeight: 0.35, homeAwayWeight: 0.25, h2hWeight: 0.20, goalTrendWeight: 0.05, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'result', safeAlternative: null,
  },
  {
    marketKey: 'double_chance_12',
    marketName: 'Double Chance (Home or Away)',
    marketGroup: 'Double Chance',
    riskCategory: 'SAFE' as const,
    minConfidence: 60, keepThreshold: 65, replaceThreshold: 45, removeThreshold: 35,
    requiredMetrics: ['form', 'homeAway', 'h2h'],
    formWeight: 0.35, homeAwayWeight: 0.25, h2hWeight: 0.20, goalTrendWeight: 0.05, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'result', safeAlternative: null,
  },
  {
    marketKey: 'over_05',
    marketName: 'Over 0.5 Goals',
    marketGroup: 'Over/Under',
    riskCategory: 'SAFE' as const,
    minConfidence: 65, keepThreshold: 70, replaceThreshold: 50, removeThreshold: 40,
    requiredMetrics: ['goalTrend', 'form'],
    formWeight: 0.20, homeAwayWeight: 0.10, h2hWeight: 0.15, goalTrendWeight: 0.40, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: null,
  },
  {
    marketKey: 'draw_no_bet_home',
    marketName: 'Draw No Bet (Home)',
    marketGroup: 'Draw No Bet',
    riskCategory: 'SAFE' as const,
    minConfidence: 62, keepThreshold: 67, replaceThreshold: 48, removeThreshold: 38,
    requiredMetrics: ['form', 'homeAway', 'h2h', 'teamStrength'],
    formWeight: 0.30, homeAwayWeight: 0.25, h2hWeight: 0.20, goalTrendWeight: 0.05, oddsWeight: 0.10, teamStrengthWeight: 0.10,
    correlationGroup: 'result', safeAlternative: 'double_chance_1x',
  },
  {
    marketKey: 'draw_no_bet_away',
    marketName: 'Draw No Bet (Away)',
    marketGroup: 'Draw No Bet',
    riskCategory: 'SAFE' as const,
    minConfidence: 62, keepThreshold: 67, replaceThreshold: 48, removeThreshold: 38,
    requiredMetrics: ['form', 'homeAway', 'h2h', 'teamStrength'],
    formWeight: 0.30, homeAwayWeight: 0.25, h2hWeight: 0.20, goalTrendWeight: 0.05, oddsWeight: 0.10, teamStrengthWeight: 0.10,
    correlationGroup: 'result', safeAlternative: 'double_chance_x2',
  },

  // ── MEDIUM RISK MARKETS ───────────────────────────────────────────────
  {
    marketKey: '1x2_home',
    marketName: 'Home Win',
    marketGroup: '1X2',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 65, keepThreshold: 70, replaceThreshold: 52, removeThreshold: 42,
    requiredMetrics: ['form', 'homeAway', 'h2h', 'teamStrength', 'odds'],
    formWeight: 0.30, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.15, oddsWeight: 0.10, teamStrengthWeight: 0.10,
    correlationGroup: 'result', safeAlternative: 'double_chance_1x',
  },
  {
    marketKey: '1x2_away',
    marketName: 'Away Win',
    marketGroup: '1X2',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 65, keepThreshold: 70, replaceThreshold: 52, removeThreshold: 42,
    requiredMetrics: ['form', 'homeAway', 'h2h', 'teamStrength', 'odds'],
    formWeight: 0.30, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.15, oddsWeight: 0.10, teamStrengthWeight: 0.10,
    correlationGroup: 'result', safeAlternative: 'double_chance_x2',
  },
  {
    marketKey: 'over_15',
    marketName: 'Over 1.5 Goals',
    marketGroup: 'Over/Under',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 65, keepThreshold: 70, replaceThreshold: 52, removeThreshold: 42,
    requiredMetrics: ['goalTrend', 'form', 'h2h'],
    formWeight: 0.20, homeAwayWeight: 0.10, h2hWeight: 0.20, goalTrendWeight: 0.35, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: 'over_05',
  },
  {
    marketKey: 'btts_yes',
    marketName: 'Both Teams to Score - Yes',
    marketGroup: 'BTTS',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 65, keepThreshold: 70, replaceThreshold: 52, removeThreshold: 42,
    requiredMetrics: ['goalTrend', 'form', 'h2h'],
    formWeight: 0.25, homeAwayWeight: 0.10, h2hWeight: 0.15, goalTrendWeight: 0.35, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'btts', safeAlternative: 'over_15',
  },
  {
    marketKey: 'btts_no',
    marketName: 'Both Teams to Score - No',
    marketGroup: 'BTTS',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 65, keepThreshold: 68, replaceThreshold: 50, removeThreshold: 40,
    requiredMetrics: ['goalTrend', 'form'],
    formWeight: 0.25, homeAwayWeight: 0.15, h2hWeight: 0.15, goalTrendWeight: 0.30, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'btts', safeAlternative: null,
  },
  {
    marketKey: 'under_25',
    marketName: 'Under 2.5 Goals',
    marketGroup: 'Over/Under',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 65, keepThreshold: 68, replaceThreshold: 50, removeThreshold: 40,
    requiredMetrics: ['goalTrend', 'h2h', 'form'],
    formWeight: 0.20, homeAwayWeight: 0.10, h2hWeight: 0.20, goalTrendWeight: 0.35, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: null,
  },
  {
    marketKey: 'over_25',
    marketName: 'Over 2.5 Goals',
    marketGroup: 'Over/Under',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 67, keepThreshold: 72, replaceThreshold: 53, removeThreshold: 43,
    requiredMetrics: ['goalTrend', 'h2h', 'form', 'teamStrength'],
    formWeight: 0.20, homeAwayWeight: 0.10, h2hWeight: 0.20, goalTrendWeight: 0.35, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: 'over_15',
  },
  {
    marketKey: 'home_and_over_15',
    marketName: 'Home Win & Over 1.5',
    marketGroup: 'Combo',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 68, keepThreshold: 73, replaceThreshold: 55, removeThreshold: 45,
    requiredMetrics: ['form', 'homeAway', 'goalTrend', 'h2h'],
    formWeight: 0.30, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.20, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'result_goals', safeAlternative: '1x2_home',
  },
  {
    marketKey: 'home_and_btts',
    marketName: 'Home Win & BTTS Yes',
    marketGroup: 'Combo',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 68, keepThreshold: 73, replaceThreshold: 55, removeThreshold: 45,
    requiredMetrics: ['form', 'homeAway', 'goalTrend', 'h2h'],
    formWeight: 0.28, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.22, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'result_btts', safeAlternative: '1x2_home',
  },
  {
    marketKey: 'away_and_over_15',
    marketName: 'Away Win & Over 1.5',
    marketGroup: 'Combo',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 68, keepThreshold: 73, replaceThreshold: 55, removeThreshold: 45,
    requiredMetrics: ['form', 'homeAway', 'goalTrend', 'h2h'],
    formWeight: 0.30, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.20, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'result_goals', safeAlternative: '1x2_away',
  },

  // ── HIGH VOLATILITY MARKETS ───────────────────────────────────────────
  {
    marketKey: '1x2_draw',
    marketName: 'Draw',
    marketGroup: '1X2',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 70, keepThreshold: 75, replaceThreshold: 58, removeThreshold: 48,
    requiredMetrics: ['form', 'h2h', 'teamStrength', 'odds'],
    formWeight: 0.25, homeAwayWeight: 0.20, h2hWeight: 0.25, goalTrendWeight: 0.10, oddsWeight: 0.10, teamStrengthWeight: 0.10,
    correlationGroup: 'result', safeAlternative: 'double_chance_1x',
  },
  {
    marketKey: 'over_35',
    marketName: 'Over 3.5 Goals',
    marketGroup: 'Over/Under',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 72, keepThreshold: 77, replaceThreshold: 60, removeThreshold: 50,
    requiredMetrics: ['goalTrend', 'h2h', 'teamStrength'],
    formWeight: 0.15, homeAwayWeight: 0.10, h2hWeight: 0.20, goalTrendWeight: 0.40, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: 'over_25',
  },
  {
    marketKey: 'under_15',
    marketName: 'Under 1.5 Goals',
    marketGroup: 'Over/Under',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 72, keepThreshold: 76, replaceThreshold: 58, removeThreshold: 48,
    requiredMetrics: ['goalTrend', 'h2h', 'form'],
    formWeight: 0.18, homeAwayWeight: 0.12, h2hWeight: 0.20, goalTrendWeight: 0.38, oddsWeight: 0.07, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: 'under_25',
  },
  {
    marketKey: '1up_home',
    marketName: '1UP Home (Win by 1+)',
    marketGroup: 'Asian Handicap',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 72, keepThreshold: 77, replaceThreshold: 60, removeThreshold: 50,
    requiredMetrics: ['form', 'homeAway', 'teamStrength', 'h2h'],
    formWeight: 0.30, homeAwayWeight: 0.25, h2hWeight: 0.15, goalTrendWeight: 0.10, oddsWeight: 0.10, teamStrengthWeight: 0.10,
    correlationGroup: 'result', safeAlternative: '1x2_home',
  },
  {
    marketKey: '1up_away',
    marketName: '1UP Away (Win by 1+)',
    marketGroup: 'Asian Handicap',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 72, keepThreshold: 77, replaceThreshold: 60, removeThreshold: 50,
    requiredMetrics: ['form', 'homeAway', 'teamStrength', 'h2h'],
    formWeight: 0.30, homeAwayWeight: 0.25, h2hWeight: 0.15, goalTrendWeight: 0.10, oddsWeight: 0.10, teamStrengthWeight: 0.10,
    correlationGroup: 'result', safeAlternative: '1x2_away',
  },
  {
    marketKey: '2up_home',
    marketName: '2UP Home (Win by 2+)',
    marketGroup: 'Asian Handicap',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 75, keepThreshold: 80, replaceThreshold: 62, removeThreshold: 52,
    requiredMetrics: ['form', 'homeAway', 'teamStrength', 'goalTrend'],
    formWeight: 0.28, homeAwayWeight: 0.25, h2hWeight: 0.12, goalTrendWeight: 0.15, oddsWeight: 0.10, teamStrengthWeight: 0.10,
    correlationGroup: 'result', safeAlternative: '1up_home',
  },
  {
    marketKey: '2up_away',
    marketName: '2UP Away (Win by 2+)',
    marketGroup: 'Asian Handicap',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 75, keepThreshold: 80, replaceThreshold: 62, removeThreshold: 52,
    requiredMetrics: ['form', 'homeAway', 'teamStrength', 'goalTrend'],
    formWeight: 0.28, homeAwayWeight: 0.25, h2hWeight: 0.12, goalTrendWeight: 0.15, oddsWeight: 0.10, teamStrengthWeight: 0.10,
    correlationGroup: 'result', safeAlternative: '1up_away',
  },
  {
    marketKey: 'exact_score_10',
    marketName: 'Correct Score 1-0',
    marketGroup: 'Correct Score',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 78, keepThreshold: 82, replaceThreshold: 65, removeThreshold: 55,
    requiredMetrics: ['form', 'goalTrend', 'teamStrength', 'h2h'],
    formWeight: 0.25, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.25, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'score', safeAlternative: '1x2_home',
  },
  {
    marketKey: 'exact_score_20',
    marketName: 'Correct Score 2-0',
    marketGroup: 'Correct Score',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 78, keepThreshold: 82, replaceThreshold: 65, removeThreshold: 55,
    requiredMetrics: ['form', 'goalTrend', 'teamStrength', 'h2h'],
    formWeight: 0.25, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.25, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'score', safeAlternative: '1x2_home',
  },
  {
    marketKey: 'exact_score_21',
    marketName: 'Correct Score 2-1',
    marketGroup: 'Correct Score',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 78, keepThreshold: 82, replaceThreshold: 65, removeThreshold: 55,
    requiredMetrics: ['form', 'goalTrend', 'teamStrength', 'h2h'],
    formWeight: 0.25, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.25, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'score', safeAlternative: 'over_15',
  },

  // ── CUSTOM LOGIC MARKETS ──────────────────────────────────────────────
  {
    marketKey: 'ht_ft_home_home',
    marketName: 'HT/FT Home/Home',
    marketGroup: 'Half Time / Full Time',
    riskCategory: 'CUSTOM' as const,
    minConfidence: 75, keepThreshold: 80, replaceThreshold: 62, removeThreshold: 52,
    requiredMetrics: ['form', 'homeAway', 'h2h', 'teamStrength'],
    formWeight: 0.30, homeAwayWeight: 0.25, h2hWeight: 0.20, goalTrendWeight: 0.05, oddsWeight: 0.10, teamStrengthWeight: 0.10,
    correlationGroup: 'result', safeAlternative: '1x2_home',
  },
  {
    marketKey: 'ht_home_win',
    marketName: 'Half Time Home Win',
    marketGroup: 'Half Time Result',
    riskCategory: 'CUSTOM' as const,
    minConfidence: 70, keepThreshold: 75, replaceThreshold: 58, removeThreshold: 48,
    requiredMetrics: ['form', 'homeAway', 'teamStrength'],
    formWeight: 0.32, homeAwayWeight: 0.28, h2hWeight: 0.15, goalTrendWeight: 0.10, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'result', safeAlternative: 'double_chance_1x',
  },
  {
    marketKey: 'ht_away_win',
    marketName: 'Half Time Away Win',
    marketGroup: 'Half Time Result',
    riskCategory: 'CUSTOM' as const,
    minConfidence: 70, keepThreshold: 75, replaceThreshold: 58, removeThreshold: 48,
    requiredMetrics: ['form', 'homeAway', 'teamStrength'],
    formWeight: 0.32, homeAwayWeight: 0.28, h2hWeight: 0.15, goalTrendWeight: 0.10, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'result', safeAlternative: 'double_chance_x2',
  },
  {
    marketKey: 'home_over_05_scored',
    marketName: 'Home Team to Score',
    marketGroup: 'Team to Score',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 65, keepThreshold: 70, replaceThreshold: 52, removeThreshold: 42,
    requiredMetrics: ['form', 'goalTrend', 'homeAway'],
    formWeight: 0.25, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.30, oddsWeight: 0.05, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: 'over_05',
  },
  {
    marketKey: 'away_over_05_scored',
    marketName: 'Away Team to Score',
    marketGroup: 'Team to Score',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 65, keepThreshold: 70, replaceThreshold: 52, removeThreshold: 42,
    requiredMetrics: ['form', 'goalTrend', 'homeAway'],
    formWeight: 0.25, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.30, oddsWeight: 0.05, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: 'over_05',
  },
  {
    marketKey: 'over_45',
    marketName: 'Over 4.5 Goals',
    marketGroup: 'Over/Under',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 78, keepThreshold: 83, replaceThreshold: 66, removeThreshold: 56,
    requiredMetrics: ['goalTrend', 'h2h', 'teamStrength'],
    formWeight: 0.12, homeAwayWeight: 0.08, h2hWeight: 0.20, goalTrendWeight: 0.45, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: 'over_35',
  },
  {
    marketKey: 'under_35',
    marketName: 'Under 3.5 Goals',
    marketGroup: 'Over/Under',
    riskCategory: 'MEDIUM' as const,
    minConfidence: 65, keepThreshold: 70, replaceThreshold: 52, removeThreshold: 42,
    requiredMetrics: ['goalTrend', 'h2h', 'form'],
    formWeight: 0.18, homeAwayWeight: 0.12, h2hWeight: 0.20, goalTrendWeight: 0.38, oddsWeight: 0.07, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: null,
  },
  {
    marketKey: 'home_clean_sheet',
    marketName: 'Home Clean Sheet',
    marketGroup: 'Clean Sheet',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 72, keepThreshold: 77, replaceThreshold: 60, removeThreshold: 50,
    requiredMetrics: ['form', 'goalTrend', 'homeAway', 'teamStrength'],
    formWeight: 0.25, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.25, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: 'btts_no',
  },
  {
    marketKey: 'away_clean_sheet',
    marketName: 'Away Clean Sheet',
    marketGroup: 'Clean Sheet',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 72, keepThreshold: 77, replaceThreshold: 60, removeThreshold: 50,
    requiredMetrics: ['form', 'goalTrend', 'homeAway', 'teamStrength'],
    formWeight: 0.25, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.25, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'goals', safeAlternative: 'btts_no',
  },
  {
    marketKey: 'away_and_btts',
    marketName: 'Away Win & BTTS Yes',
    marketGroup: 'Combo',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 70, keepThreshold: 75, replaceThreshold: 57, removeThreshold: 47,
    requiredMetrics: ['form', 'homeAway', 'goalTrend', 'h2h'],
    formWeight: 0.28, homeAwayWeight: 0.20, h2hWeight: 0.15, goalTrendWeight: 0.22, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'result_btts', safeAlternative: '1x2_away',
  },
  {
    marketKey: 'draw_and_btts',
    marketName: 'Draw & BTTS Yes',
    marketGroup: 'Combo',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 73, keepThreshold: 78, replaceThreshold: 60, removeThreshold: 50,
    requiredMetrics: ['form', 'h2h', 'goalTrend'],
    formWeight: 0.22, homeAwayWeight: 0.18, h2hWeight: 0.25, goalTrendWeight: 0.22, oddsWeight: 0.08, teamStrengthWeight: 0.05,
    correlationGroup: 'result_btts', safeAlternative: 'btts_yes',
  },
  {
    marketKey: 'home_win_to_nil',
    marketName: 'Home Win to Nil',
    marketGroup: 'Win to Nil',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 74, keepThreshold: 79, replaceThreshold: 62, removeThreshold: 52,
    requiredMetrics: ['form', 'homeAway', 'goalTrend', 'teamStrength'],
    formWeight: 0.28, homeAwayWeight: 0.22, h2hWeight: 0.15, goalTrendWeight: 0.20, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'result_goals', safeAlternative: '1x2_home',
  },
  {
    marketKey: 'away_win_to_nil',
    marketName: 'Away Win to Nil',
    marketGroup: 'Win to Nil',
    riskCategory: 'HIGH_VOLATILITY' as const,
    minConfidence: 74, keepThreshold: 79, replaceThreshold: 62, removeThreshold: 52,
    requiredMetrics: ['form', 'homeAway', 'goalTrend', 'teamStrength'],
    formWeight: 0.28, homeAwayWeight: 0.22, h2hWeight: 0.15, goalTrendWeight: 0.20, oddsWeight: 0.10, teamStrengthWeight: 0.05,
    correlationGroup: 'result_goals', safeAlternative: '1x2_away',
  },
]

async function main() {
  console.log('Seeding 38 market rules...')

  for (const market of markets) {
    await prisma.marketRule.upsert({
      where: { marketKey: market.marketKey },
      update: market,
      create: market,
    })
  }

  console.log(`✅ Seeded ${markets.length} market rules successfully`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())